#!/bin/sh

profile=ec2gitlab 
cd /home/centos/gitlab-aws/configuration

#"ap-northeast-1" "ap-northeast-2" "ap-south-1" "ap-southeast-1"
#"ap-southeast-2" "ca-central-1" "eu-central-1" "eu-north-1"
#"eu-west-1" "eu-west-2" "eu-west-3" "sa-east-1"

for region in "us-east-1" "us-east-2" "us-west-1" "us-west-2"
do
    date
    time packer build -var name=build -var profile="${profile}" -var aws_region="${region}" \
    | tee ~/"packer.${region}.out"

done
